In [4]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from  sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [5]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
########preprocessing the data
#1.removing the irrelevant columns 
data = data.drop(columns = ["RowNumber","CustomerId","Surname"],axis = 1)

In [7]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [8]:
#2.encoding the categorical data  into numerical data
level_encoder_gender = LabelEncoder()

data["Gender"] = level_encoder_gender.fit_transform(data["Gender"])

data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [9]:
#3.one hot encoding for the categorical data with more than 2 categories
one_hot_encoder_geography = OneHotEncoder()
geoEncoder = one_hot_encoder_geography.fit_transform(data[["Geography"]])
geoEncoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [10]:
one_hot_encoder_geography.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [11]:
geoEncoder = geoEncoder.toarray()

In [12]:

geoEncoder_df  = pd.DataFrame(geoEncoder,columns = one_hot_encoder_geography.get_feature_names_out())

In [13]:
geoEncoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [14]:
#4. combining the one hot encoded data with the orioginal data and dropping the original categorical column
data = pd.concat([data,geoEncoder_df],axis = 1)
data = data.drop("Geography",axis = 1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [15]:
####saving the encoders 
with open("level_encoder_gender.pkl","wb") as f:
    pickle.dump(level_encoder_gender,f)
    
with open("one_hot_encoder_geography.pkl","wb") as f:
    pickle.dump(one_hot_encoder_geography,f)

In [16]:
########dividing the data into features and target variables 
y = data["Exited"]
X = data.drop("Exited",axis = 1)


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,1.0,0.0,0.0

In [18]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [19]:
#5. transforming the data using standard scaler 
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [20]:
X_train_scaled.shape

(8000, 12)

In [21]:
#save the scaler 
with open("scaler.pkl","wb") as f:
    pickle.dump(scaler,f)

ANN Implementation

In [22]:
from tensorflow import keras 
from keras.layers import Dense
from keras.models import Sequential
from keras.callbacks import EarlyStopping, TensorBoard
from keras.utils import plot_model
from keras.activations import relu, sigmoid
import datetime

In [23]:
model = Sequential(
    [
        Dense(64 , activation=relu, input_shape=(X_train_scaled.shape[1],), name = "input"),
        Dense(32 , activation=relu, name = "h1"),
        Dense(1, activation = sigmoid, name = "output_layer")
    ]
)

/Users/abhijeetmalik/Desktop/projects/ANN Classifier/venv/lib/python3.11/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ h1 (Dense)                      │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_layer (Dense)            │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
#making the optimizer for the backpropogation
opt = keras.optimizers.Adam(learning_rate= 0.001)

In [26]:
##compile the model
model.compile(optimizer = opt, loss = "binary_crossentropy", metrics = ["accuracy"])

In [40]:
## tensorboard call back for visualzing the training process
log_dir = "log/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir = log_dir, histogram_freq=1,)

In [32]:
## Set up Early call back to stop the training when the model starts to overfit
early_stopping = EarlyStopping(monitor = "val_loss", patience=20, restore_best_weights=True)

In [33]:
history = model.fit(X_train_scaled, y_train, epochs = 100,
                     validation_data = (X_test_scaled, y_test), callbacks = [early_stopping, tensorflow_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.8689 - loss: 0.3124 - val_accuracy: 0.8595 - val_loss: 0.3354
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 750us/step - accuracy: 0.8700 - loss: 0.3114 - val_accuracy: 0.8650 - val_loss: 0.3329
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 761us/step - accuracy: 0.8711 - loss: 0.3107 - val_accuracy: 0.8615 - val_loss: 0.3333
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 731us/step - accuracy: 0.8695 - loss: 0.3094 - val_accuracy: 0.8660 - val_loss: 0.3366
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 753us/step - accuracy: 0.8700 - loss: 0.3093 - val_accuracy: 0.8630 - val_loss: 0.3353
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 751us/step - accuracy: 0.8720 - loss: 0.3068 - val_accuracy: 0.8615 - val_loss: 0.3345
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 740us/step - accuracy: 0.8730 - loss: 0.3062 - val_accuracy: 0.8605 - val_loss: 0.3367
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 743us/step - accuracy: 0.8740 - loss: 0.3055 - val_accuracy: 0.8585 - val_loss: 0.3387
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step - accuracy: 0.8719 - loss: 0.3044 - val_accuracy: 0.8620 - val_loss: 0.3387
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 726us/step - accuracy: 0.8750 - loss: 0.3032 - val_accuracy: 0.8560 - val_loss: 0.3409
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step - accuracy: 0.8729 - loss: 0.3029 - val_accuracy: 0.8610 - val_loss: 0.3392
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 737us/step - accuracy: 0.8742 - loss: 0.3012 - val_accuracy: 0.8610 - val_loss: 0.3345
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 750us/step - accuracy: 0.8731 - loss: 0.2992 - val_accuracy: 0.8640 - val_loss: 0.3358
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 760us/step - accuracy: 0.8764 - loss: 0.2990 - val_accuracy: 0.8600 - val_loss: 0.3414
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 738us/step - accuracy: 0.8759 - loss: 0.2975 - val_accuracy: 0.8595 - val_loss: 0.3372
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.8769 - loss: 0.2961 - val_accuracy: 0.8635 - val_loss: 0.3364
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 751us/step - accuracy: 0.8784 - loss: 0.2952 - val_accuracy: 0.8625 - val_loss: 0.3395
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 728us/step - accuracy: 0.8794 - loss: 0.2935 - val_accuracy: 0.8620 - val_loss: 0.3411
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step - accuracy: 0.8781 - loss: 0.2910 - val_accuracy: 0.8540 - val_loss: 0.3502
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - accuracy: 0.8779 - loss: 0.2924 - val_accuracy: 0.8610 - val_loss: 0.3422
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 724us/step - accuracy: 0.8788 - loss: 0.2897 - val_accuracy: 0.8605 - val_loss: 0.3480
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - accuracy: 0.8780 - loss: 0.2885 - val_accuracy: 0.8610 - val_loss: 0.3443

In [34]:
model.save("model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [39]:
%tensorboard --logdir log/fit20260227-145658

Reusing TensorBoard on port 6008 (pid 67603), started 0:02:08 ago. (Use '!kill 67603' to kill it.)

In [44]:
##load the trained ANN model , load all the models - ANN , scalar , one hot encoder , label encoder
#load the model 
model = keras.models.load_model("model.h5")

#load the encoder and scaler objects 
with open("one_hot_encoder_geography.pkl","rb") as f:
    one_hot_encoder_geography = pickle.load(f)

with open("scaler.pkl","rb") as f:
    scaler = pickle.load(f)

with open("level_encoder_gender.pkl","rb") as f:
    level_encoder_gender = pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [60]:
####now we take the new data point for testing our model 
new_data = {
    "CreditScore": 600,
    "Geography": "France",
    "Gender": "Male",
    "Age": 40,
    "Tenure": 3,
    "Balance": 60000,
    "NumOfProducts": 2,
    "HasCrCard": 1,
    "IsActiveMember": 1,
    "EstimatedSalary": 50000
}

In [61]:
input_df = pd.DataFrame([new_data])

In [62]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [63]:
#now doing the preprocesing stepf for this new data point
#1. encoding the categorical data  into numerical data
input_df["Gender"] = level_encoder_gender.transform(input_df["Gender"])

#2. one hot encoding for the categorical data with more than 2 categories
geoEncoder_df = one_hot_encoder_geography.transform(input_df[["Geography"]]).toarray()
geoEncoder_df

array([[1., 0., 0.]])

In [64]:
input_df = pd.concat([input_df.drop(["Geography"], axis = 1), pd.DataFrame(geoEncoder_df, columns = one_hot_encoder_geography.get_feature_names_out())], axis = 1)

In [65]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [66]:
# now lets do the scaling for this new data point
input_df_scaled = scaler.transform(input_df)

In [67]:
prediction = model.predict(input_df_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

array([[0.0212678]], dtype=float32)

In [68]:
#analysing the prediction 
if prediction[0][0] > 0.5:
    print("the customer is likely to churn")
else:
    print("the customer is not likely to churn")

the customer is not likely to churn